-- Widen the data_centers status machine and add the fields needed by the
-- new discover-data-centers merge pipeline (aliases/operators/partners for
-- fuzzy matching, power + energization context, and an extraction_confidence
-- that is distinct from verification_status: the former is "how sure was the
-- LLM extraction", the latter is "did an automated source check pass").
ALTER TABLE public.data_centers DROP CONSTRAINT IF EXISTS data_centers_lifecycle_stage_check;
ALTER TABLE public.data_centers ADD CONSTRAINT data_centers_lifecycle_stage_check
  CHECK (lifecycle_stage IN (
    'land_banked', 'planned', 'under_construction', 'operational',
    'announced', 'on_hold', 'decommissioned', 'cancelled', 'unknown'
  ));

ALTER TABLE public.data_centers
  ADD COLUMN IF NOT EXISTS aliases TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS operators TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS partners TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS full_ambition_mw NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS power_source TEXT CHECK (power_source IN ('gas', 'solar', 'nuclear', 'mixed', 'unknown')),
  ADD COLUMN IF NOT EXISTS power_notes TEXT,
  ADD COLUMN IF NOT EXISTS estimated_energization TEXT,
  ADD COLUMN IF NOT EXISTS risks TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS extraction_confidence TEXT CHECK (extraction_confidence IN ('high', 'medium', 'low'));

-- Backfill the new operators[] from the existing single operator_name so
-- fuzzy matching has something to compare against for pre-existing rows.
UPDATE public.data_centers
SET operators = ARRAY[operator_name]
WHERE operator_name IS NOT NULL AND operators = '{}'::text[];

-- Audit trail for lifecycle_stage changes, so the weekly changelog can report
-- "what changed" instead of only "what the current state is".
CREATE TABLE IF NOT EXISTS public.data_center_status_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  data_center_id UUID NOT NULL REFERENCES public.data_centers(id) ON DELETE CASCADE,
  lifecycle_stage TEXT NOT NULL,
  source_id UUID REFERENCES public.data_center_sources(id) ON DELETE SET NULL,
  note TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS data_center_status_history_dc_idx
  ON public.data_center_status_history(data_center_id, changed_at DESC);

ALTER TABLE public.data_center_status_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view data center status history" ON public.data_center_status_history;
CREATE POLICY "Public can view data center status history" ON public.data_center_status_history FOR SELECT USING (true);

-- Weekly delta briefs generated by generate-dc-changelog.
CREATE TABLE IF NOT EXISTS public.data_center_weekly_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start DATE NOT NULL UNIQUE,
  markdown TEXT NOT NULL,
  total_live_mw NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_uc_mw NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_planned_mw NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_announced_mw NUMERIC(12,2) NOT NULL DEFAULT 0,
  projects_added INTEGER NOT NULL DEFAULT 0,
  projects_updated INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.data_center_weekly_briefs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view data center weekly briefs" ON public.data_center_weekly_briefs;
CREATE POLICY "Public can view data center weekly briefs" ON public.data_center_weekly_briefs FOR SELECT USING (true);
